name: CI

on:
  pull_request:
    branches: [main , dev]
  push:
    branches: [main]

jobs:
  

  docker:
    name: Docker Build (Test + Build)
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_USE_MOCK=${{ secrets.VITE_REAL_API_URL && 'false' || 'true' }} \
            --build-arg VITE_REAL_API_URL=${{ secrets.VITE_REAL_API_URL }} \
            -t soundcloud-frontend .

  sync:
    name: Sync to Monorepo
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
        with:
          path: frontend-source

      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: Tunify-T8/Sound_Cloud_Clone-Team8
          token: ${{ secrets.MONOREPO_PAT }}
          path: monorepo

      - name: Sync frontend into monorepo
        run: |
          rm -rf monorepo/frontend
          rsync -av --exclude='.git' frontend-source/ monorepo/frontend/

      - name: Commit and push to monorepo
        run: |
          cd monorepo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add frontend/
          git diff --cached --quiet || git commit -m "Sync frontend from ${{ github.sha }}"
          git push
